### ISSUE TITLE
Anonymous Posting on Forums

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#118]
### **As a** 
User

### **I want to** 
Use the bot to post on my behalf

### **In order to** 
Keep my identity anonymous in public

***

### Acceptance Criteria
- [x] User must be able to trigger the functionality via command
- [x] User will be presented with a GUI to write his/her post
- [x] User must be able to select which forum to anonymously submit his/her post based on the allowed forums set by the admins
- [x] Upon submission, the bot will create a post on a specified forum with the content that the user has written
- [x] Submissions must be logged in a channel, that can be defined by the admins, and visible only to the Admins to prevent abuse and misuse.
- [x] The log should include the original author and the content
- [x] The Admins must be able to toggle the feature on or off
- [x] The Admins must be able to set which forums to allow the anonymous posting feature on.

### Things to consider
- Consider giving each post a unique ID (preferrable a UUID) to allow the user to reply to his/her anonymous post while maintaining anonymity in a future feature. You don't have to implement this, just consider to have this in the future

**Comment by Jedddy** [comment]
An idea as per sir Rei:


- [ ] Remove UUID->Forum Post relationship table
- [ ] Encrypt instead the thread ID with the user id as passphrase (salt is required, must add in .env file)
- [ ] Send the encrypted text to the user instead of UUID
- [ ] When replying, User will provide encrypted text
- [ ] System will decrypt the ID and use it to reply to the thread
