### ISSUE TITLE
Research on Discord Bot API calls

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#163]
Conduct research on how to call PPH bot functions via URL endpoints using python

## Goals
- To be able to perform PPH bot actions through an external app (eg. Job Ads Portal) via API calls
- Document all findings

**Comment by Zarasuto** [comment]
I have initially found 3 potential ways to perform PPH bot actions using API.
1. Using discord interactions, it mainly uses an HTTP call to perform commands. but the problem is that it is rate limited by 200 calls per day.
Sources:
https://discord.com/developers/docs/interactions/application-commands#authorizing-your-application
https://stackoverflow.com/questions/75815526/how-to-invoke-a-discord-bot-command-via-rest-api

2. Using the combination of fastAPI and discord bot. manually invoking a command through the use of HTTP call. 
Example.

main.py
```
`from fastapi import FastAPI
import uvicorn
import asyncio
from superbot import ProgPhil
from API.APIcommand import helloCommand

app = FastAPI()

@app.on_event("startup")
async def startup_event():
  asyncio.create_task(bot.start('token'))

if __name__ == '__main__':
    bot = ProgPhilBot()
    app.include_router(helloCommand(bot).router)
    uvicorn.run(app, host="localhost", port=8000)`
```
command.py
```
from discord.ext import commands
import discord
from fastapi import APIRouter

class Basic(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def hello(self, ctx):
        await ctx.send("Hello!")

async def setup(bot):
    await bot.add_cog(Basic(bot))
```

API.py
```
from fastapi import APIRouter,Request
from superbot import ProgPhil


class helloCommand():

    context = None
    router = APIRouter(
        prefix="/hello",
        tags=["commands"],
        responses={404: {"description": "Not found"}}
    )
    #ProgPhil is the bot
    def __init__(self,ctx:ProgPhil):
        helloCommand.context=ctx

    @router.get("/")
    async def command_hello():
        hello_command = helloCommand.context.get_command('hello')
        hello_context = await helloCommand.context.get_context(None)
        await helloCommand.context.invoke(hello_command,hello_context)
        return {"success":"finally!"}
```
this method mainly uses **bot,invoke** to call a command.
The problem with this approach is that the commands all requires a context object. which is impossible to perform using API calls.  
It can be easily solved by not using any context-based actions. for example, a message.
```
async def hello_message():
    # Replace these with your actual values
    test_guild = bot.get_guild(GUILD_ID)
    test_channel = test_guild.get_channel(CHANNEL_ID)

    test_message = discord.Message(content="Hello!", author=test_guild.me, channel=test_channel)
    await bot.dispatch("message", test_message)
```

3. Using a webhook, it uses POST requests to send directly to discord. but it may be separate from the bot and not in-line with the bot's purpose.
This is an example code.
import requests
import json

```
webhook_url = 'YOUR_WEBHOOK_URL'

# Create an embed with an image
embed = {
    'title': 'Image Embed',
    'image': {'url': 'IMAGE_URL'}  # Replace with the actual image URL
}

# Create the payload with the embed
payload = {
    'content': 'Here is an image:',
    'embeds': [embed]
}

# Send the payload as a POST request to the webhook URL
response = requests.post(webhook_url, data=json.dumps(payload), headers={'Content-Type': 'application/json'})

# Check if the message was sent successfully
if response.status_code == 204:
    print('Image sent successfully!')
else:
    print('Failed to send image:', response.text)
```
Source:
https://discord.com/developers/docs/resources/webhook#execute-webhook
https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks

**Comment by Zarasuto** [comment]
https://github.com/ProgrammingPhilippines/progphil-bot/wiki/Research-and-Findings

Done.
