### ISSUE TITLE
Research on deployment and infrastructure for Discord bots

### ISSUE THREAD

**Issue by kylecdrck** [ProgrammingPhilippines/progphil-bot#29]
### **As an** 
Operations

### **I want to** 
Research on creating an infrastructure for discord bots

### **In order to** 
Implement an infrastructure for development, integration, deployment, and all related activities for discord bots

***

### Acceptance Criteria

- [x] Documentation on the findings available in the Wiki

**Comment by ssuish** [comment]
Currently researching on related infrastructure and discord bot hosting services aside from AWS and Azure Cloud. I am traversing the internet and discord dev communities hoping I will get an insight. Should I post my findings here as comment?

**Comment by kylecdrck** [comment]
@ssuish yes, please

**Comment by ssuish** [comment]
This is my opinionated suggestions based on what I read on their documentation and product services. I choose them based on the pricing, reputation, and reliability. Since we just starting, I disregarded probable hosting services that may cost above 5$, AWS/Azure/G-Cloud services, and other service provider offering free trial. 

**Pipe's self hosted server:** Free

- @voo#6115 (pipe) actively offers his self-hosted server to host our discord bot. We can use it as temporary server host until we needed to scale up our bot to a proper server.   

**Sparkedhost:** 1$/mo
Offers:

- 50% shared CPU
- 512mb RAM/ 5GB SSD
- SFTP Access/ DDoS Protection
- Free MySQL DB/Git Support
- Dedicated Bot IP
- Most popular Discord bot hosting service provider.

Limitations:

- Closest Server is in Singapore, expected heavy traffic and latency.
- Unmanaged and offers Basic support.

Link: [Sparkedhost Services](https://sparkedhost.com/discord-bot-hosting)

**Digital Ocean** 4$/mo
Offers:

- Basic Droplet plan is suitable for low traffic servers
- 512 Mib Memory/1 vCPU/ 500 Gib Transfer/10 Gib SSD
- Best for low-medium load and low traffic apps.
- running on shared CPU that uses 1st gen or older Intel Xeon/AMD Epyc processors.
- Documentation for setting up Discord bot is available.

Limitations:

- Droplets have a maximum network throughput limit of 2 Gbps.
- Root password resets are not available for operating systems with internally-managed passwords.

Link [Digital Ocean Plans](https://docs.digitalocean.com/products/droplets/concepts/choosing-a-plan/)

**Comment by CunningBard** [comment]
* Oracle Cloud provides a tiny but good free VPS.

* Google Cloud has a free always-tier VPS.
    > 1 non-preemptible e2-micro VM instance per month in one of the following US regions:
        * Oregon: us-west1
        * Iowa: us-central1
        * South Carolina: us-east1

* Amazon AWS also has a one-year free VPS.

**Comment by CunningBard** [comment]
The first thought I had was a Raspberry Pi but uh, out of stock, but cloud is the best choice

**Comment by Jedddy** [comment]
> This is my opinionated suggestions based on what I read on their documentation and product services. I choose them based on the pricing, reputation, and reliability. Since we just starting, I disregarded probable hosting services that may cost above 5$, AWS/Azure/G-Cloud services, and other service provider offering free trial.
> 
> **Pipe's self hosted server:** Free
> 
> * @voo#6115 (pipe) actively offers his self-hosted server to host our discord bot. We can use it as temporary server host until we needed to scale up our bot to a proper server.
> 
> **Sparkedhost:** 1$/mo Offers:
> 
> * 50% shared CPU
> * 512mb RAM/ 5GB SSD
> * SFTP Access/ DDoS Protection
> * Free MySQL DB/Git Support
> * Dedicated Bot IP
> * Most popular Discord bot hosting service provider.
> 
> Limitations:
> 
> * Closest Server is in Singapore, expected heavy traffic and latency.
> * Unmanaged and offers Basic support.
> 
> Link: [Sparkedhost Services](https://sparkedhost.com/discord-bot-hosting)
> 
> **Digital Ocean** 4$/mo Offers:
> 
> * Basic Droplet plan is suitable for low traffic servers
> * 512 Mib Memory/1 vCPU/ 500 Gib Transfer/10 Gib SSD
> * Best for low-medium load and low traffic apps.
> * running on shared CPU that uses 1st gen or older Intel Xeon/AMD Epyc processors.
> * Documentation for setting up Discord bot is available.
> 
> Limitations:
> 
> * Droplets have a maximum network throughput limit of 2 Gbps.
> * Root password resets are not available for operating systems with 
![Screenshot_2023-01-14-21-28-35-1849468352~2](https://user-images.githubusercontent.com/104408560/212474197-de2a5b5a-8879-4ed8-959d-d12592556355.png)
internally-managed passwords.
> 
> Link [Digital Ocean Plans](https://docs.digitalocean.com/products/droplets/concepts/choosing-a-plan/)

I hosted a bot at sparked host, used dallas(?) Server i think. All seems well, bot latency was like 29-32ms
